import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getFeaturedEvents } from "../hooks/eventHooks";
import EventList from "../components/events/EventList";

const Home = () => {
	const featuredEvents = getFeaturedEvents();

	return (
		<>
			<Head>
				<title>Next Events</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					<EventList items={featuredEvents} />
				</div>
			</main>
		</>
	);
};

export default Home;
